/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversoRouteImport } from './routes/universo'
import { Route as PanteaoRouteImport } from './routes/panteao'
import { Route as LendasRouteImport } from './routes/lendas'
import { Route as AventureirosRouteImport } from './routes/aventureiros'
import { Route as IndexRouteImport } from './routes/index'

const UniversoRoute = UniversoRouteImport.update({
  id: '/universo',
  path: '/universo',
  getParentRoute: () => rootRouteImport,
} as any)
const PanteaoRoute = PanteaoRouteImport.update({
  id: '/panteao',
  path: '/panteao',
  getParentRoute: () => rootRouteImport,
} as any)
const LendasRoute = LendasRouteImport.update({
  id: '/lendas',
  path: '/lendas',
  getParentRoute: () => rootRouteImport,
} as any)
const AventureirosRoute = AventureirosRouteImport.update({
  id: '/aventureiros',
  path: '/aventureiros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aventureiros': typeof AventureirosRoute
  '/lendas': typeof LendasRoute
  '/panteao': typeof PanteaoRoute
  '/universo': typeof UniversoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aventureiros': typeof AventureirosRoute
  '/lendas': typeof LendasRoute
  '/panteao': typeof PanteaoRoute
  '/universo': typeof UniversoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aventureiros': typeof AventureirosRoute
  '/lendas': typeof LendasRoute
  '/panteao': typeof PanteaoRoute
  '/universo': typeof UniversoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aventureiros' | '/lendas' | '/panteao' | '/universo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aventureiros' | '/lendas' | '/panteao' | '/universo'
  id: '__root__' | '/' | '/aventureiros' | '/lendas' | '/panteao' | '/universo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AventureirosRoute: typeof AventureirosRoute
  LendasRoute: typeof LendasRoute
  PanteaoRoute: typeof PanteaoRoute
  UniversoRoute: typeof UniversoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universo': {
      id: '/universo'
      path: '/universo'
      fullPath: '/universo'
      preLoaderRoute: typeof UniversoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panteao': {
      id: '/panteao'
      path: '/panteao'
      fullPath: '/panteao'
      preLoaderRoute: typeof PanteaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lendas': {
      id: '/lendas'
      path: '/lendas'
      fullPath: '/lendas'
      preLoaderRoute: typeof LendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aventureiros': {
      id: '/aventureiros'
      path: '/aventureiros'
      fullPath: '/aventureiros'
      preLoaderRoute: typeof AventureirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AventureirosRoute: AventureirosRoute,
  LendasRoute: LendasRoute,
  PanteaoRoute: PanteaoRoute,
  UniversoRoute: UniversoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
